### ISSUE TITLE
Public APK Distribution?

### ISSUE THREAD

**Issue by thatfiredev** [horaciocome1/reaque#25]
I'm actually opening this issue for 2 reasons:
1. Having the google-services.json file doesn't really help us;
2. I think we should consider distributing the APK on the website.

## The google-services.json
Although we're using your google-services.json file, the only SHA key that has been added to the Firebase Console belongs to you, @horaciocome1 . So that means we cannot login to Firebase Authentication, because the SHA keys from our laptops were not added to t he Firebase Console, therefore they're not allowed to login.

I'd suggest removing the json file from the repository and adding instructions for developers to create their own Firebase Project, get their own json file and add the file to their fork of the project.

## Distributing the APK
Of course, if everyone has their own Firebase Project, the users, data, config, files, etc will all be different. And this is not what we want. We want everyone to use a single database. That's why we need a release APK. This APK will contain your google-services.json file and will be signed with a release SHA key. I'd recommend having a look at  [Publish your app](https://developer.android.com/studio/publish) to better understand [how to sign your APK](https://developer.android.com/studio/publish/app-signing).

I also saw #14 and I know you can't yet publish the APK to the Playstore, but maybe it could be published on the website, where everyone can download it and install on their devices.

**Comment by horaciocome1** [comment]
Hi!
Yes. You're completely right.

By now you should be able to download the apk file[ here](https://reaque.firebaseapp.com/#download) :)

**Comment by horaciocome1** [comment]
Now one can find public APK directly here on releases
