### ISSUE TITLE
some users are not getting their posts showing

### ISSUE THREAD

**Issue by horaciocome1** [horaciocome1/reaque#3]
user matilde dont have posts showing cant find why

**Comment by horaciocome1** [comment]
it was a firebase variable name problem

**Comment by masudr4n4** [comment]
@horaciocome1 how can i download  the app?for use it on my device

**Comment by horaciocome1** [comment]
Hi @maaudrana!
I so happy to see your interest obtaining the app.
Right now the only thing you can get is the code, then run it using your android studio targeting your phone.
I cant manage to get the app in the app store. I am looking forward to upload the apk here under /executables. If you find it ok to download this way, you can do.

Thanks

**Comment by masudr4n4** [comment]
Actually  i am a bug-hunter besides other works ,wants to test your app.thats why asking ,i don't  have enough  knowledge  to compile  your app.tnx for reply

**Comment by horaciocome1** [comment]
I will make sure you get the app as soon as it get available on the store.
Thanks
